app:
    image: my-app
    volumes:
        - .:/var/www/html/
       # - .:/var/www/html/adminer
#        - ./logs/symfony:/var/www/symfony/app/logs
    tty: true
php:
    image: my-php
    volumes_from:
        - app
    links:
        - db
        - mailcatcher
    ports:
        - 80:80
        - 9000:9000
db:
    image: mysql
    ports:
        - 3306:3306
    volumes_from:
        - app
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: bach
        MYSQL_USER: peter
        MYSQL_PASSWORD: apekop01
mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080

#composer:
#    image: composer/composer
#    volumes:
#        - .:/app
#    #usage:  docker run --rm -v $(pwd):/app composer/composer install (self-update, etc)
