data:
    image: debian:jessie
    volumes:
        - .:/var/www/html/
        - ~/Projects/bach3/data/esdata:/usr/share/elasticsearch/data
    tty: true
mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - "1025:1025"
        - "1080:1080"
memcached:
    image: memcached
    ports:
        - "11211:11211"
php:
    build: ./docker/php
    volumes_from:
        - data
    links:
        - db
        - mailcatcher
        - memcached
        - elasticsearch
    ports:
        - "80:80"
db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: bach
        MYSQL_USER: peter
        MYSQL_PASSWORD: apekop01
elasticsearch:
    build: ./docker/es
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes_from:
        - data
