app:
    #container_name: volumes
    build: ./docker/app
    volumes:
        - .:/var/www/html/
        - /var/lib/mysql
        - /usr/share/elasticsearch/data
    tty: true
php:
    #container_name: web
    build: ./docker/php
    volumes_from:
        - app
    links:
        - db
        - mailcatcher
        - memcached
        - elasticsearch
    ports:
        - 80:80
db:
    #container_name: db
    image: mysql:5.6
    ports:
        - 3306:3306
    volumes_from:
        - app
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: bach
        MYSQL_USER: peter
        MYSQL_PASSWORD: apekop01
mailcatcher:
    image: yappabe/mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
memcached:
    image: memcached
    ports:
        - 11211:11211
elasticsearch:
    image: elasticsearch:1.7
    ports:
        - 9200:9200
        - 9300:9300