<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BachRepository extends EntityRepository
{
    public function findTitles()
    {
        $query = $this->_em->createQueryBuilder()
               ->select('b')
               ->from('AppBundle:Bach','b')
               ->where('b.id > 1560')
               ->andWhere('b.part = 1')
//               ->setParameter('id', $id)
               ->getQuery()
               ->getResult();

        return $query;
    }

}
