<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BachRepository extends EntityRepository
{
    public function findTitles()
    {
        $query = $this->_em->createQueryBuilder()
               ->select('b')
               ->from('AppBundle:Bach','b')
               ->where('b.id > 1560')
               ->andWhere('b.part = 1')
               ->getQuery()
               ->getResult();

        return $query;
    }

    public function findParts($opus)
    {
        $query = $this->_em->createQueryBuilder()
               ->select('b')
               ->from('AppBundle:Bach','b')
               ->where("SUBSTRING(b.title,1,11) = '$opus'")
//               ->andWhere('b.part = 1')
               ->getQuery();



        return $query->getResult();
    }

    public function find248()
    {
        $query = $this->_em->createQueryBuilder()
               ->select('b')
               ->from('AppBundle:Bach','b')
               ->where("b.opus = 'BWV 248'")
               ->orderBy('b.id')
               ->getQuery();

        return $query->getResult();
    }



}
