<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * PartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartRepository extends EntityRepository
{
    //todo: remove method when conversion done
    public function getPartsJoined()
    {
        $query = $this->_em->createQuery(
            'SELECT p, o.opus, b.conductor, b.ensemble, b.performer, b.date, b.album, b.track
            FROM AppBundle:Part p
             LEFT JOIN AppBundle:Opus o
               WHERE p.opus = o.id
            LEFT JOIN AppBundle:Bach b
            WHERE SUBSTRING(b.title,1,7) = o.opus AND p.partnumber = b.part'

        );

        return $query->getResult();
    }

}
